/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"


  export interface PortfolioInterface extends Interface {
    getFunction(nameOrSignature: "acceptAdmin" | "addManager" | "admin" | "allocate" | "cancelPendingAdmin" | "createEnvelope" | "deleteEnvelope" | "deposit" | "envelopes" | "managers" | "moveFunds" | "pendingAdmin" | "proposeAdmin" | "removeManager" | "rescueTokenFromEnvelope" | "setWithdrawalAddress" | "token" | "unallocated" | "withdrawFromEnvelope" | "withdrawUnallocated" | "withdrawalAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminTransferCancelled" | "AdminTransferProposed" | "AdminTransferred" | "Allocated" | "Deposited" | "EnvelopeCreated" | "EnvelopeDeleted" | "EnvelopeWithdrawn" | "FundsMoved" | "ManagerAdded" | "ManagerRemoved" | "TokenRescued" | "UnallocatedWithdrawn" | "WithdrawalAddressSet"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'addManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'allocate', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelPendingAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'createEnvelope', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'deleteEnvelope', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'envelopes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'managers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'moveFunds', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pendingAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rescueTokenFromEnvelope', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWithdrawalAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'unallocated', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFromEnvelope', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawUnallocated', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawalAddress', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'acceptAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelPendingAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEnvelope', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteEnvelope', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'envelopes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'managers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moveFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rescueTokenFromEnvelope', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWithdrawalAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unallocated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFromEnvelope', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawUnallocated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawalAddress', data: BytesLike): Result;
  }


    export namespace AdminTransferCancelledEvent {
      export type InputTuple = [admin: AddressLike, cancelledPendingAdmin: AddressLike];
      export type OutputTuple = [admin: string, cancelledPendingAdmin: string];
      export interface OutputObject {admin: string, cancelledPendingAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace AdminTransferProposedEvent {
      export type InputTuple = [currentAdmin: AddressLike, proposedAdmin: AddressLike];
      export type OutputTuple = [currentAdmin: string, proposedAdmin: string];
      export interface OutputObject {currentAdmin: string, proposedAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace AdminTransferredEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace AllocatedEvent {
      export type InputTuple = [index: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [index: bigint, amount: bigint];
      export interface OutputObject {index: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace DepositedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EnvelopeCreatedEvent {
      export type InputTuple = [index: BigNumberish, envelope: AddressLike, name: BytesLike];
      export type OutputTuple = [index: bigint, envelope: string, name: string];
      export interface OutputObject {index: bigint, envelope: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EnvelopeDeletedEvent {
      export type InputTuple = [index: BigNumberish];
      export type OutputTuple = [index: bigint];
      export interface OutputObject {index: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EnvelopeWithdrawnEvent {
      export type InputTuple = [index: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [index: bigint, amount: bigint];
      export interface OutputObject {index: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace FundsMovedEvent {
      export type InputTuple = [from: BigNumberish, to: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [from: bigint, to: bigint, amount: bigint];
      export interface OutputObject {from: bigint, to: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace ManagerAddedEvent {
      export type InputTuple = [manager: AddressLike];
      export type OutputTuple = [manager: string];
      export interface OutputObject {manager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace ManagerRemovedEvent {
      export type InputTuple = [manager: AddressLike];
      export type OutputTuple = [manager: string];
      export interface OutputObject {manager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace TokenRescuedEvent {
      export type InputTuple = [index: BigNumberish, rescueToken: AddressLike, amount: BigNumberish];
      export type OutputTuple = [index: bigint, rescueToken: string, amount: bigint];
      export interface OutputObject {index: bigint, rescueToken: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace UnallocatedWithdrawnEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace WithdrawalAddressSetEvent {
      export type InputTuple = [newWithdrawalAddress: AddressLike];
      export type OutputTuple = [newWithdrawalAddress: string];
      export interface OutputObject {newWithdrawalAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



  export interface Portfolio extends BaseContract {

    connect(runner?: ContractRunner | null): Portfolio;
    waitForDeployment(): Promise<this>;

    interface: PortfolioInterface;


  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>




    acceptAdmin: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >



    addManager: TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >



    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >



    allocate: TypedContractMethod<
      [index: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    cancelPendingAdmin: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >



    createEnvelope: TypedContractMethod<
      [name: BytesLike, ],
      [bigint],
      'nonpayable'
    >



    deleteEnvelope: TypedContractMethod<
      [index: BigNumberish, ],
      [void],
      'nonpayable'
    >



    deposit: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    envelopes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >



    managers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >



    moveFunds: TypedContractMethod<
      [from: BigNumberish, to: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    pendingAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >



    proposeAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >



    removeManager: TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >



    rescueTokenFromEnvelope: TypedContractMethod<
      [index: BigNumberish, rescueToken_: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    setWithdrawalAddress: TypedContractMethod<
      [newWithdrawalAddress: AddressLike, ],
      [void],
      'nonpayable'
    >



    token: TypedContractMethod<
      [],
      [string],
      'view'
    >



    unallocated: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    withdrawFromEnvelope: TypedContractMethod<
      [index: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    withdrawUnallocated: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    withdrawalAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >



    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptAdmin'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addManager'): TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allocate'): TypedContractMethod<
      [index: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelPendingAdmin'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEnvelope'): TypedContractMethod<
      [name: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deleteEnvelope'): TypedContractMethod<
      [index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'envelopes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'managers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moveFunds'): TypedContractMethod<
      [from: BigNumberish, to: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pendingAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposeAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeManager'): TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rescueTokenFromEnvelope'): TypedContractMethod<
      [index: BigNumberish, rescueToken_: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWithdrawalAddress'): TypedContractMethod<
      [newWithdrawalAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unallocated'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFromEnvelope'): TypedContractMethod<
      [index: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawUnallocated'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawalAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AdminTransferCancelled'): TypedContractEvent<AdminTransferCancelledEvent.InputTuple, AdminTransferCancelledEvent.OutputTuple, AdminTransferCancelledEvent.OutputObject>;
getEvent(key: 'AdminTransferProposed'): TypedContractEvent<AdminTransferProposedEvent.InputTuple, AdminTransferProposedEvent.OutputTuple, AdminTransferProposedEvent.OutputObject>;
getEvent(key: 'AdminTransferred'): TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
getEvent(key: 'Allocated'): TypedContractEvent<AllocatedEvent.InputTuple, AllocatedEvent.OutputTuple, AllocatedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'EnvelopeCreated'): TypedContractEvent<EnvelopeCreatedEvent.InputTuple, EnvelopeCreatedEvent.OutputTuple, EnvelopeCreatedEvent.OutputObject>;
getEvent(key: 'EnvelopeDeleted'): TypedContractEvent<EnvelopeDeletedEvent.InputTuple, EnvelopeDeletedEvent.OutputTuple, EnvelopeDeletedEvent.OutputObject>;
getEvent(key: 'EnvelopeWithdrawn'): TypedContractEvent<EnvelopeWithdrawnEvent.InputTuple, EnvelopeWithdrawnEvent.OutputTuple, EnvelopeWithdrawnEvent.OutputObject>;
getEvent(key: 'FundsMoved'): TypedContractEvent<FundsMovedEvent.InputTuple, FundsMovedEvent.OutputTuple, FundsMovedEvent.OutputObject>;
getEvent(key: 'ManagerAdded'): TypedContractEvent<ManagerAddedEvent.InputTuple, ManagerAddedEvent.OutputTuple, ManagerAddedEvent.OutputObject>;
getEvent(key: 'ManagerRemoved'): TypedContractEvent<ManagerRemovedEvent.InputTuple, ManagerRemovedEvent.OutputTuple, ManagerRemovedEvent.OutputObject>;
getEvent(key: 'TokenRescued'): TypedContractEvent<TokenRescuedEvent.InputTuple, TokenRescuedEvent.OutputTuple, TokenRescuedEvent.OutputObject>;
getEvent(key: 'UnallocatedWithdrawn'): TypedContractEvent<UnallocatedWithdrawnEvent.InputTuple, UnallocatedWithdrawnEvent.OutputTuple, UnallocatedWithdrawnEvent.OutputObject>;
getEvent(key: 'WithdrawalAddressSet'): TypedContractEvent<WithdrawalAddressSetEvent.InputTuple, WithdrawalAddressSetEvent.OutputTuple, WithdrawalAddressSetEvent.OutputObject>;

    filters: {

      'AdminTransferCancelled(address,address)': TypedContractEvent<AdminTransferCancelledEvent.InputTuple, AdminTransferCancelledEvent.OutputTuple, AdminTransferCancelledEvent.OutputObject>;
      AdminTransferCancelled: TypedContractEvent<AdminTransferCancelledEvent.InputTuple, AdminTransferCancelledEvent.OutputTuple, AdminTransferCancelledEvent.OutputObject>;


      'AdminTransferProposed(address,address)': TypedContractEvent<AdminTransferProposedEvent.InputTuple, AdminTransferProposedEvent.OutputTuple, AdminTransferProposedEvent.OutputObject>;
      AdminTransferProposed: TypedContractEvent<AdminTransferProposedEvent.InputTuple, AdminTransferProposedEvent.OutputTuple, AdminTransferProposedEvent.OutputObject>;


      'AdminTransferred(address,address)': TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
      AdminTransferred: TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;


      'Allocated(uint256,uint256)': TypedContractEvent<AllocatedEvent.InputTuple, AllocatedEvent.OutputTuple, AllocatedEvent.OutputObject>;
      Allocated: TypedContractEvent<AllocatedEvent.InputTuple, AllocatedEvent.OutputTuple, AllocatedEvent.OutputObject>;


      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;


      'EnvelopeCreated(uint256,address,bytes32)': TypedContractEvent<EnvelopeCreatedEvent.InputTuple, EnvelopeCreatedEvent.OutputTuple, EnvelopeCreatedEvent.OutputObject>;
      EnvelopeCreated: TypedContractEvent<EnvelopeCreatedEvent.InputTuple, EnvelopeCreatedEvent.OutputTuple, EnvelopeCreatedEvent.OutputObject>;


      'EnvelopeDeleted(uint256)': TypedContractEvent<EnvelopeDeletedEvent.InputTuple, EnvelopeDeletedEvent.OutputTuple, EnvelopeDeletedEvent.OutputObject>;
      EnvelopeDeleted: TypedContractEvent<EnvelopeDeletedEvent.InputTuple, EnvelopeDeletedEvent.OutputTuple, EnvelopeDeletedEvent.OutputObject>;


      'EnvelopeWithdrawn(uint256,uint256)': TypedContractEvent<EnvelopeWithdrawnEvent.InputTuple, EnvelopeWithdrawnEvent.OutputTuple, EnvelopeWithdrawnEvent.OutputObject>;
      EnvelopeWithdrawn: TypedContractEvent<EnvelopeWithdrawnEvent.InputTuple, EnvelopeWithdrawnEvent.OutputTuple, EnvelopeWithdrawnEvent.OutputObject>;


      'FundsMoved(uint256,uint256,uint256)': TypedContractEvent<FundsMovedEvent.InputTuple, FundsMovedEvent.OutputTuple, FundsMovedEvent.OutputObject>;
      FundsMoved: TypedContractEvent<FundsMovedEvent.InputTuple, FundsMovedEvent.OutputTuple, FundsMovedEvent.OutputObject>;


      'ManagerAdded(address)': TypedContractEvent<ManagerAddedEvent.InputTuple, ManagerAddedEvent.OutputTuple, ManagerAddedEvent.OutputObject>;
      ManagerAdded: TypedContractEvent<ManagerAddedEvent.InputTuple, ManagerAddedEvent.OutputTuple, ManagerAddedEvent.OutputObject>;


      'ManagerRemoved(address)': TypedContractEvent<ManagerRemovedEvent.InputTuple, ManagerRemovedEvent.OutputTuple, ManagerRemovedEvent.OutputObject>;
      ManagerRemoved: TypedContractEvent<ManagerRemovedEvent.InputTuple, ManagerRemovedEvent.OutputTuple, ManagerRemovedEvent.OutputObject>;


      'TokenRescued(uint256,address,uint256)': TypedContractEvent<TokenRescuedEvent.InputTuple, TokenRescuedEvent.OutputTuple, TokenRescuedEvent.OutputObject>;
      TokenRescued: TypedContractEvent<TokenRescuedEvent.InputTuple, TokenRescuedEvent.OutputTuple, TokenRescuedEvent.OutputObject>;


      'UnallocatedWithdrawn(uint256)': TypedContractEvent<UnallocatedWithdrawnEvent.InputTuple, UnallocatedWithdrawnEvent.OutputTuple, UnallocatedWithdrawnEvent.OutputObject>;
      UnallocatedWithdrawn: TypedContractEvent<UnallocatedWithdrawnEvent.InputTuple, UnallocatedWithdrawnEvent.OutputTuple, UnallocatedWithdrawnEvent.OutputObject>;


      'WithdrawalAddressSet(address)': TypedContractEvent<WithdrawalAddressSetEvent.InputTuple, WithdrawalAddressSetEvent.OutputTuple, WithdrawalAddressSetEvent.OutputObject>;
      WithdrawalAddressSet: TypedContractEvent<WithdrawalAddressSetEvent.InputTuple, WithdrawalAddressSetEvent.OutputTuple, WithdrawalAddressSetEvent.OutputObject>;

    };
  }
