[profile.default]
src = "contracts"
out = "out-foundry"
libs = ["lib"]
test = "foundry"
cache_path = "forge-cache"
solc = "0.8.34"

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
]
