#!/usr/bin/env node
/**
 * Regenerates frontend ABI files from compiled Hardhat artifacts.
 *
 * Run after modifying contracts:
 *   npm run contracts:compile
 *   npm run sync-abi
 *
 * Output files:
 *   frontend/src/lib/abi/Portfolio.js  — PortfolioABI (JSON), PortfolioBytecode, ERC20ABI
 *   frontend/src/lib/abi/Envelope.js   — EnvelopeABI (JSON)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ARTIFACTS = resolve(ROOT, 'contracts/artifacts/contracts/contracts');
const FRONTEND_ABI = resolve(ROOT, 'frontend/src/lib/abi');

function readArtifact(contractName) {
  const path = resolve(ARTIFACTS, `${contractName}.sol/${contractName}.json`);
  if (!existsSync(path)) {
    console.error(`Artifact not found: ${path}`);
    console.error('Run `npm run contracts:compile` first.');
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, 'utf8'));
}

// ERC-20 ABI — kept here since it's a standard interface, not from our contracts
const ERC20ABI = [
  'function balanceOf(address account) view returns (uint256)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function decimals() view returns (uint8)',
  'function symbol() view returns (string)',
];

function generatePortfolioJs(artifact) {
  const abi = JSON.stringify(artifact.abi, null, 2);
  const bytecode = artifact.bytecode;
  const erc20 = JSON.stringify(ERC20ABI, null, 2);

  return `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// To regenerate: npm run contracts:compile && npm run sync-abi

export const PortfolioABI = ${abi};

export const PortfolioBytecode = '${bytecode}';

// Minimal ERC-20 ABI for approval flows (USDC, etc.)
export const ERC20ABI = ${erc20};
`;
}

function generateEnvelopeJs(artifact) {
  const abi = JSON.stringify(artifact.abi, null, 2);

  return `// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// To regenerate: npm run contracts:compile && npm run sync-abi

export const EnvelopeABI = ${abi};
`;
}

const portfolio = readArtifact('Portfolio');
const envelope = readArtifact('Envelope');

writeFileSync(resolve(FRONTEND_ABI, 'Portfolio.js'), generatePortfolioJs(portfolio));
writeFileSync(resolve(FRONTEND_ABI, 'Envelope.js'), generateEnvelopeJs(envelope));

console.log('ABI sync complete:');
console.log(`  Portfolio: ${portfolio.abi.length} entries, bytecode ${portfolio.bytecode.length} chars`);
console.log(`  Envelope:  ${envelope.abi.length} entries`);
