// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.34;

import {Test} from "forge-std/Test.sol";

import {Portfolio} from "../../contracts/Portfolio.sol";
import {MockERC20} from "../../contracts/mocks/MockERC20.sol";
import {PortfolioHandler} from "./PortfolioHandler.sol";

/// @title Portfolio Invariant Tests
///
/// Verifies two families of system-level properties across arbitrary call
/// sequences generated by the Foundry fuzzer:
///
///   Fund conservation — no USDC is created or destroyed inside the system.
///   Access control    — privilege boundaries cannot be crossed.
///
/// The fuzzer calls functions on PortfolioHandler, which acts as a
/// controlled wrapper around the real Portfolio + Envelope contracts.
/// Ghost variables in the handler track cumulative totals and flag any
/// unexpected successes from unprivileged callers.
contract PortfolioInvariant is Test {
    Portfolio   internal portfolio;
    MockERC20   internal token;
    PortfolioHandler internal handler;

    address internal admin           = makeAddr("admin");
    address internal manager         = makeAddr("manager");
    address internal stranger        = makeAddr("stranger");
    address internal withdrawalAddr  = makeAddr("withdrawal");

    function setUp() public {
        token = new MockERC20("Mock USDC", "MUSDC", 6);

        vm.startPrank(admin);
        portfolio = new Portfolio(address(token), withdrawalAddr);
        portfolio.addManager(manager);
        vm.stopPrank();

        handler = new PortfolioHandler(
            portfolio,
            token,
            admin,
            manager,
            stranger,
            withdrawalAddr
        );

        // All fuzzer calls go through the handler
        targetContract(address(handler));

        // Prevent the fuzzer from impersonating system contracts directly
        excludeSender(address(portfolio));
        excludeSender(address(token));
        excludeSender(address(handler));
    }

    // ─── Fund conservation ────────────────────────────────────────────────────

    /// @notice Total deposited == funds still in system + funds already withdrawn.
    ///
    /// Equivalently: no USDC can be created or destroyed inside the portfolio
    /// system regardless of which operations the fuzzer sequences.
    function invariant_fundConservation() external view {
        assertEq(
            handler.totalSystemBalance() + handler.ghost_totalWithdrawn(),
            handler.ghost_totalDeposited(),
            "Fund conservation: deposits != system balance + withdrawals"
        );
    }

    /// @notice portfolio.unallocated() is defined as the portfolio's own token
    ///         balance; verify the two never diverge.
    function invariant_unallocatedMatchesPortfolioBalance() external view {
        assertEq(
            portfolio.unallocated(),
            token.balanceOf(address(portfolio)),
            "unallocated() != token.balanceOf(portfolio)"
        );
    }

    /// @notice Every token that leaves the portfolio system must arrive at the
    ///         withdrawal address — never at any other address.
    function invariant_withdrawalsReachOnlyWithdrawalAddress() external view {
        uint256 received =
            token.balanceOf(withdrawalAddr) - handler.ghost_withdrawalInitialBalance();
        assertEq(
            received,
            handler.ghost_totalWithdrawn(),
            "Withdrawn amount != withdrawal address balance increase"
        );
    }

    // ─── Access control ───────────────────────────────────────────────────────

    /// @notice An address that is neither admin nor manager must never succeed
    ///         in any state-changing operation on the portfolio.
    function invariant_strangerCannotChangeState() external view {
        assertFalse(
            handler.ghost_strangerSucceeded(),
            "Stranger succeeded in a privileged operation"
        );
    }

    /// @notice A manager must not be able to change the withdrawal address;
    ///         that power belongs exclusively to the admin.
    function invariant_managerCannotChangeWithdrawalAddress() external view {
        assertFalse(
            handler.ghost_managerChangedWithdrawal(),
            "Manager succeeded in changing the withdrawal address"
        );
    }

    /// @notice A manager must not be able to modify the manager set (add or
    ///         remove); those operations belong exclusively to the admin.
    function invariant_managerCannotModifyManagerSet() external view {
        assertFalse(
            handler.ghost_managerAddedManager(),
            "Manager succeeded in adding a new manager"
        );
        assertFalse(
            handler.ghost_managerRemovedManager(),
            "Manager succeeded in removing a manager"
        );
    }
}
