name: Slither Static Analysis

on:
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  slither:
    name: Run Slither analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - run: pip install "crytic-compile" --upgrade
      - uses: crytic/slither-action@v0.4.2
        id: slither
        with:
          node-version: '22'
          target: 'contracts/'
          slither-args: '--checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/'
          sarif: results.sarif
          fail-on: none
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
